name: pipeline
channels:
  - conda-forge
dependencies:
  - cloudpickle
  - dask
  - fsspec
  - zstandard
  - hypothesis
  - pre-commit
  - pytest
  - tox
  - pip
  - pip:
    - serialize
    # - lazy_import
