[build-system]
requires = ["setuptools", "wheel", "setuptools_scm[toml]"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[tool.isort]
line_length = 88  # Black default

[tool.check-manifest]
ignore = [".pre-commit-config.yaml"]